# Generated by Django 5.1.1 on 2024-09-11 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['video'])]),
        ),
    ]
