# Generated by Django 5.1.1 on 2024-09-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='language',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
