# Generated by Django 5.1.1 on 2024-09-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_subtitle_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='text',
        ),
        migrations.AddField(
            model_name='subtitle',
            name='file',
            field=models.FileField(default=0, upload_to='subs'),
            preserve_default=False,
        ),
    ]
