# Generated by Django 5.1.1 on 2024-09-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_remove_subtitle_text_subtitle_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DurationField()),
                ('end_time', models.DurationField()),
                ('text', models.TextField()),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='mysite.subtitle')),
            ],
        ),
    ]
